### ISSUE TITLE
An error occurred while Click 'Chat Completion' Button in word, '-2147012894(80072ee2)', Why?

### ISSUE THREAD

**Issue by sxbug** [analyticsinmotion/add-gpt-chatbot-to-microsoft-word#1]
Env: Win 10 64bit Chs version, Office 2019, API Key Installed
Debug:
Dim objCurlHttp As Object
  Set objCurlHttp = CreateObject("MSXML2.serverXMLHTTP")

  With objCurlHttp
    .Open "POST", strURL, False
    .SetRequestHeader "Content-type", "application/json"
    .SetRequestHeader "Authorization", "Bearer " + strAPIKey
    .Send (strJSONdata)      //Stuck here  ***************************************
    
    Dim strResponse As String
    strResponse = .ResponseText

Why?     Thanks

**Comment by rossarmstrong** [comment]
Hi @sxbug, thank you for submitting this issue. We believe the issue you are referring to is actually a request timeout error. It will occur when there is an outage across the OpenAI chat channel (chat.openai.com). You can monitor any OpenAI outages at this link: https://status.openai.com/. We need to add some additional error handling to the code in order to provide a more meaningful alert message when there is an outage with ChatGPT. I hope this answers your question.

**Comment by orange1027** [comment]
I also met a similar problem. How can I solve it

**Comment by rossarmstrong** [comment]
Hello @sxbug and @orange1027. We have just released a new version that patches the issue you have raised. Please update your Chat.bas file to the latest 0.1.1 version (it is in the src/windows directory of this repository). I will also close this issue. Should you have any further issues please let us know.
